//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GunzAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gun()
        {
            this.GunUsers = new HashSet<GunUser>();
        }
    
        public int GunID { get; set; }
        public string GunName { get; set; }
        public string GunDescription { get; set; }
        public Nullable<int> GunTypeID { get; set; }
        public Nullable<int> GunAutomaticID { get; set; }
    
        public virtual GunAutomatic GunAutomatic { get; set; }
        public virtual GunType GunType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GunUser> GunUsers { get; set; }
    }
}
