//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GunzAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GunzEntities : DbContext
    {
        public GunzEntities()
            : base("name=GunzEntities")
        {
            base.Configuration.ProxyCreationEnabled = false;
            base.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gun> Guns { get; set; }
        public virtual DbSet<GunAutomatic> GunAutomatics { get; set; }
        public virtual DbSet<GunType> GunTypes { get; set; }
        public virtual DbSet<GunUser> GunUsers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
